### ISSUE TITLE
How do i install this?

### ISSUE THREAD

**Issue by kgrosvenor** [GroundSix/communicator-sdk#1]

**Comment by jmsfwk** [comment]
Install using Composer:

    composer install groundsix/communicator-sdk

This package requires PHP 7.1

**Comment by kgrosvenor** [comment]
I updated my version but Credentials class is not found

` / - Uncaught Error: Class 'GroundSix\Communicator\Resources\Credentials' not found in /Users/kierangrosvenor/Documents/projects/communicator-test/index.php:24
Stack trace:
#0 {main}
  thrown in /Users/kierangrosvenor/Documents/projects/communicator-test/index.php on line 24

`

**Comment by kgrosvenor** [comment]
USING like this removes errors, do docs need to be updated?

use GroundSix\Communicator\Credentials as Credentials;

**Comment by jmsfwk** [comment]
Yes, I have updated the README and it should mirror to Github shortly.

This package is now only a low level wrapper around Communicator's API.

It explicitly exposes the methods available and validates the response from Communicator. It doesn't provide any higher level methods like in the example in the old README.

**Comment by kgrosvenor** [comment]
Thanks buddy looking forward to seeing it, we currently use a .NET integration - but need to use php as thats what my system is written in, it saves us having a micro service that doesn't always seem to work 100%!

**Comment by jmsfwk** [comment]
I'll see what I can do about open sourcing the higher level package next week.
